name: Roblox520 Auto Update

on:
  schedule:
    - cron: "0 12 * * *"  # 每天UTC时间12:00运行
  workflow_dispatch:      # 允许手动触发
  push:
    branches:
      - main
    paths:
      - 'domains.txt'    # 当域名列表变更时也触发

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: pip install requests urllib3
        
      - name: Run update script
        run: python update_hosts.py
        
      - name: Commit and push changes
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add hosts
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update hosts file [skip ci]"
          git push
